### ISSUE TITLE
Crash on chat: Cannot start a runtime from within a runtime. 

### ISSUE THREAD

**Issue by SinanAkkoyun** [Ai00-X/ai00_server#108]
I followed the release installation 1:1 and get this when trying to chat (world 5 7B model used):

```sh
2024-05-01T11:37:08.762Z WARN  [salvo_core::conn::quinn::builder] accept failed error=h3::Error { timeout: true }
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/multi_thread/mod.rs:86:9:
Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
stack backtrace:
   0:     0x55896ba79c36 - std::backtrace_rs::backtrace::libunwind::trace::hd6ffdc229294c06f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x55896ba79c36 - std::backtrace_rs::backtrace::trace_unsynchronized::h991f79b6e9960513
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55896ba79c36 - std::sys_common::backtrace::_print_fmt::hf4ebe716f7ccda10
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:68:5
   3:     0x55896ba79c36 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h410d4c66be4e37f9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55896baa9440 - core::fmt::rt::Argument::fmt::he0ff0e0e188c0db5
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/rt.rs:142:9
   5:     0x55896baa9440 - core::fmt::write::he40921d4802ce2ac
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/fmt/mod.rs:1120:17
   6:     0x55896ba75c2f - std::io::Write::write_fmt::h5de5a4e7037c9b20
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/io/mod.rs:1846:15
   7:     0x55896ba79a14 - std::sys_common::backtrace::_print::hd8e2e3f655086663
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55896ba79a14 - std::sys_common::backtrace::print::h11c067a88e3bdb22
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55896ba7af67 - std::panicking::default_hook::{{closure}}::h8c832ecb03fde8ea
  10:     0x55896ba7acc9 - std::panicking::default_hook::h1633e272b4150cf3
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:292:9
  11:     0x55896ba7b3f8 - std::panicking::rust_panic_with_hook::hb164d19c0c1e71d4
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:781:13
  12:     0x55896ba7b299 - std::panicking::begin_panic_handler::{{closure}}::h0369088c533c20e9
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:651:13
  13:     0x55896ba7a136 - std::sys_common::backtrace::__rust_end_short_backtrace::hc11d910daf35ac2e
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys_common/backtrace.rs:171:18
  14:     0x55896ba7b024 - rust_begin_unwind
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
  15:     0x55896ac33365 - core::panicking::panic_fmt::ha6effc2775a0749c
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
  16:     0x55896b09b206 - tokio::runtime::runtime::Runtime::block_on::h236c3b94d0531535
  17:     0x55896aef6159 - <salvo_core::http::body::req::h3::H3ReqBody<S,B> as http_body::Body>::poll_frame::h9c3ab5a84c65b7fd
  18:     0x55896b5926b3 - <salvo_core::http::body::req::ReqBody as http_body::Body>::poll_frame::haaaaac6e93e7f6f7
  19:     0x55896b0caaae - <http_body_util::limited::Limited<B> as http_body::Body>::poll_frame::h7fef667ee65c52a8
  20:     0x55896aeb9040 - <http_body_util::combinators::collect::Collect<T> as core::future::future::Future>::poll::hba3a3cb62e1ef858
  21:     0x55896ad775b7 - salvo_core::http::request::Request::payload_with_max_size::{{closure}}::h90ee54d78872b723
  22:     0x55896ada789f - <ai00_server::api::oai::chat::chat_completions as salvo_core::handler::Handler>::handle::{{closure}}::h4f5be904dc5344b5
  23:     0x55896b568b03 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hb28957cd110b6e04
  24:     0x55896b567760 - <salvo_extra::logging::Logger as salvo_core::handler::Handler>::handle::{{closure}}::hbf46c3ccc555d11e
  25:     0x55896b54c1e6 - <salvo_cors::CorsHandler as salvo_core::handler::Handler>::handle::{{closure}}::he7610e3c7fe04666
  26:     0x55896ac4e614 - salvo_core::routing::FlowCtrl::call_next::{{closure}}::h17a339185c45214c
  27:     0x55896ac4f289 - <salvo_core::service::HyperHandler as hyper::service::service::Service<http::request::Request<B>>>::call::{{closure}}::hcc7b34e4f9837243
  28:     0x55896ac49471 - salvo_core::conn::quinn::builder::process_request::{{closure}}::h90ca7725dfd38f78
  29:     0x55896ac4cd08 - salvo_core::conn::quinn::builder::Builder::serve_connection::{{closure}}::{{closure}}::hdb63e0da3869bff5
  30:     0x55896ac83dc1 - tokio::runtime::task::core::Core<T,S>::poll::hde3f4917fe65e1da
  31:     0x55896acf1fd6 - tokio::runtime::task::raw::poll::h897d9a2ce97853e6
  32:     0x55896b9e4dab - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h5580559aa7fc3226
  33:     0x55896b9e3f60 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h33487fc931f25ef4
  34:     0x55896b9de829 - tokio::runtime::context::runtime::enter_runtime::ha8b88187cfcabdbe
  35:     0x55896b9e34b8 - tokio::runtime::scheduler::multi_thread::worker::run::hdf914a06223ce372
  36:     0x55896b9cc453 - <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll::hb802c3173971faa4
  37:     0x55896b9c9757 - tokio::runtime::task::core::Core<T,S>::poll::h618eec163362862f
  38:     0x55896b9c383a - tokio::runtime::task::harness::Harness<T,S>::poll::h3fec009e5bae21ce
  39:     0x55896b9e92f0 - tokio::runtime::blocking::pool::Inner::run::h273d4aee736610e9
  40:     0x55896b9d4147 - std::sys_common::backtrace::__rust_begin_short_backtrace::he7f606401dc0250f
  41:     0x55896b9dd1c9 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h451162fef8767b8a
  42:     0x55896ba80e15 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6b630278c760b971
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  43:     0x55896ba80e15 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h70462b441b6c0e1f
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  44:     0x55896ba80e15 - std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
                               at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/sys/pal/unix/thread.rs:108:17
  45:     0x7fe5fb213ac3 - start_thread
                               at ./nptl/pthread_create.c:442:8
  46:     0x7fe5fb2a5850 - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  47:                0x0 - <unknown>

```

**Comment by SinanAkkoyun** [comment]
Same happens when building from source

**Comment by cryscan** [comment]
Try disabling tls in `assets/configs/Config.toml`.
![6a96c6e3e4d0107063d307128f6c1486](https://github.com/Ai00-X/ai00_server/assets/16053640/a3bdf4f8-4607-49cc-a3f1-c014e6d08748)

**Comment by navr32** [comment]
Hi all ! Very good work. I have the same problem too.  So stop TLS work..
